#!/usr/bin/with-contenv bash

if [ ! -f /tmp/state/99-cron ]; then
        echo ' '
        echo 'Cron Initialization Sleeping for 10 seconds'
        sleep 10
        echo '59 23 * * * logrotate -f /etc/logrotate.d/* >/dev/null 2>&1' >>/assets/cron/crontab.txt
	mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/99-cron
fi

echo 'Starting cron..'
/usr/bin/crontab /assets/cron/crontab.txt
exec /usr/sbin/crond -f -l 8

