#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="tinc"

check_container_initialized
check_service_initialized init

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then 
	DEBUG=9
else 
	DEBUG=${DEBUG:-0}
fi

liftoff

### Startup Tinc
print_info "Starting Tinc ${TINC_VERSION} for Host '${NODE}' on VPN '${NETWORK}'"
exec tinc --net=${NETWORK} start --no-detach --debug=${DEBUG} --logfile=/var/log/tinc/tinc.${NETWORK}.log
