#!/usr/bin/with-contenv bash

source /assets/functions/*
PROCESS_NAME="tinc"
check_initialized
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then 
	DEBUG=9
else 
	DEBUG=${DEBUG:-0}
fi

liftoff

### Startup Tinc
print_info "Starting Tinc ${TINC_VERSION} for Host '${NODE}' on VPN '${NETWORK}'"
exec tinc --net=${NETWORK} start --no-detach --debug=${DEBUG} --logfile=/var/log/tinc/tinc.${NETWORK}.log
