#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="tinc"

check_container_initialized
check_service_initialized init

if var_true $DEBUG_MODE ; then
	DEBUG=9
else 
	DEBUG=${DEBUG:-0}
fi

liftoff

### Startup Tinc
print_info "Starting Tinc ${TINC_VERSION} for Host '${NODE}' on VPN '${NETWORK}'"
exec tinc --net=${NETWORK} start --no-detach --debug=${DEBUG} --logfile=/var/log/tinc/tinc.${NETWORK}.log
