#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="tinc"

check_container_initialized
check_service_initialized init
liftoff

### Startup Tinc
print_start "Starting Tinc ${TINC_VERSION} for Host '${NODE}' on VPN '${NETWORK}'"
tinc --net=${NETWORK} start --no-detach --debug=${DEBUG} --logfile=${LOG_PATH}/${NETWORK}.log
